config/routes.rb
Rails.application.routes.draw do
  get 'user/index'
  root "peoples#index"
  # get 'peoples/index'
  # get 'peoples/show'
  resources :peoples do 
    collection do
      get :person
      get :librarian
      get :student
    end
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :update, Person, user: user
  
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/librarian.rb
class Librarian < Person
	resourcify
end

app/models/person.rb
class Person < ApplicationRecord
	has_one_attached :profile_image
	belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/student.rb
class Student < Person
	resourcify
end

app/models/user.rb
class User < ApplicationRecord
  rolify :before_add => :before_add_method
    def before_add_method(role)
      "this is method call by rolify"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/peoples_controller.rb
class PeoplesController < ApplicationController

  def index
    @peoples = Person.all
  end

  def show
    @peoples = Person.find(params[:id])
  end

  def person
    @peoples = Person.all
  end

  def librarian
    @librarians = Librarian.all
  end

  def student
    @students = Student.all
  end

  def new
    @peoples = Person.new
  end

  def create

    @peoples = Person.new(per_params)
    if @peoples.save
      BackgroundJobsJob.perform_later(@peoples.id)
       # BackgroundJobsJob.set(wait: 1.minute).perform_later(@peoples.id)
      redirect_to person_peoples_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @peoples = Person.find(params[:id])
  end

  def update
    @peoples = Person.find(params[:id])
  

    if @peoples.update(per_params)
      redirect_to person_peoples_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @peoples = Person.find(params[:id])
    @peoples.destroy

    redirect_to root_path, status: :see_other
  end


  private
    def per_params
      params.require(:person).permit(:name, :surname, :email,:profile_image)
    end
end

 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/peoples_helper.rb
module PeoplesHelper
	def format_name(name=nil)
		"Mr. #{name}"
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibraryMs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/peoples/_form.html.erb
<center>
<fieldset>
   <h1>Form</h1>
  <%= form_with model: peoples, url: (@peoples.new_record? ? peoples_path : peoples_path) do |form| %>
    <div>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </div>
    <br>
    <div>
      <%= form.label :surname %><br>
      <%= form.text_field :surname %><br>
    </div>
    <br>
    <div>
      <%= form.label :email %><br>
      <%= form.text_field :email %><br>
    </div>
    <br>
    <div>
      <%= form.file_field :profile_image %>
    </div>
    <br>

    <div>
      <%= form.submit "submit", class: "btn btn-primary" %>
    </div>

  <% end %>
</fieldset>
</center>  

app/views/peoples/edit.html.erb
<h1> Edit </h1>
<%= render "form",peoples: @peoples%>

app/views/peoples/index.html.erb
<marquee behavior="" direction="right"><h1 style="color: blue;">Welcome To My Library</h1></marquee> 
<center >
<h3>List of Peoples</h3>
<%= link_to 'Peoples', person_peoples_path%>

<br><br>

<h3>List of Librarians</h3>
<%= link_to 'Librarian', librarian_peoples_path%>

<br><br>

<h3>List of Students</h3>
<%= link_to 'Student', student_peoples_path%>

<br><br>

<%= link_to "Add New User", new_people_path %>
</center>

app/views/peoples/librarian.html.erb
<h1>Librarians</h1>

<ul>
  <% @librarians.each do |p| %>
    <li>
    	<%= link_to p.name, people_path(p.id) %>
    </li>
  <% end %>
</ul>

app/views/peoples/new.html.erb
<h1> new </h1>
<%= render "form",peoples: @peoples%>

app/views/peoples/person.html.erb
<h1>Peoples</h1>

<ul>
  <% @peoples.each do |p| %>
    <li>
    	<%= link_to p.name, people_path(p.id) %>
    </li>
  <% end %>
</ul>

app/views/peoples/show.html.erb
<center>
	<div>
		<%if @peoples.profile_image.attached?%>
			<%= image_tag @peoples.profile_image,width: 200,height: 200 ,class: "circle" %>
		<%end%>
	</div>

	<h1><%= format_name(@peoples.name) %></h1>

	<p><%= @peoples.surname %></p>

	<ul>
		<li><%= link_to "Edit", edit_people_path %></li>
  		<li><%= link_to "Destroy", peoples_path(@peoples.id), data: {
                    turbo_method: :delete,turbo_confirm: "Are you sure?"} %></li>
	</ul>
</center>

app/views/peoples/student.html.erb
<h1>Students</h1>

<ul>
  <% @students.each do |p| %>
    <li>
    	<%= link_to p.name, people_path(p.id) %>
    </li>
  <% end %>
</ul>